### ISSUE TITLE
Magefan Blog Post Content section

### ISSUE THREAD

**Issue by ppeyman** [breezefront/module-breeze-magefan-blog#1]
Hi dear support
Magefan Blog Post Content Section doesn't Compatible with breeze frontend.
when i add Widget to page Cloumn in Page Builder doesn't works well and Post Content Collapse doesn't close or open 

They ride on each other Column left or right
![image](https://user-images.githubusercontent.com/13271466/230321017-99d181ae-c46e-46dc-9394-9448f7452c16.png)

and for Collapse without breeze : 

![image](https://user-images.githubusercontent.com/13271466/230321449-b6330a72-8e0e-495f-bc1d-266cba038e92.png)

with breeze show like below : 

![image](https://user-images.githubusercontent.com/13271466/230322544-8309d821-c310-4aac-abfd-ed8a0b513155.png)

**Comment by vovayatsyuk** [comment]
1. How can I add post content? I can't find this feature.
2. What widget should I add?

**Comment by ppeyman** [comment]
> 1. How can I add post content? I can't find this feature.
> 2. What widget should I add?

the feature is premium for Extra Plans and for basic or free version doesn't show 
but i can add file who create that widget or send for you full version of extra plan

Magefan/BlogExtra/view/frontend/templates/widget/contents-php.phtml 
and 
Magefan/BlogExtra/view/frontend/templates/widget/contents.phtml

files:
https://easyupload.io/fqb80d



Thank You

**Comment by vovayatsyuk** [comment]
Sorry, but I don't have the pro version and I can't make an integration using these files.

**Comment by ppeyman** [comment]
> 

dear vovayatsyuk 

how can i send it for you ? with mail or antoher way ?

**Comment by vovayatsyuk** [comment]
Send it to ###. Thank you.

**Comment by ppeyman** [comment]
> Send it to ###. Thank you.

done

**Comment by vovayatsyuk** [comment]
I still don't see the post contents. What should I do? Additionally, it asks me for a license key.

**Comment by vovayatsyuk** [comment]
Another problem I stumbled with is that module is not compatible with magento 2.4.6. I get error when saving blog post:

```
TypeError: Zend_Filter::addFilter(): Argument #1 ($filter) must be of type Zend_Filter_Interface, Magento\Framework\Stdlib\DateTime\Filter\DateTime given, called in /magento2/vendor/magento/zendframework1/library/Zend/Filter/Input.php on line 687 and defined in /magento2/vendor/magento/zendframework1/library/Zend/Filter.php:60
Stack trace:
#0 /magento2/vendor/magento/zendframework1/library/Zend/Filter/Input.php(687): Zend_Filter->addFilter()
#1 /magento2/vendor/magento/zendframework1/library/Zend/Filter/Input.php(785): Zend_Filter_Input->_filter()
#2 /magento2/vendor/magento/zendframework1/library/Zend/Filter/Input.php(381): Zend_Filter_Input->_process()
#3 /magento2/app/code/Magefan/Blog/Controller/Adminhtml/Post/Save.php(185): Zend_Filter_Input->getUnescaped()
#4 /magento2/app/code/Magefan/Community/Controller/Adminhtml/Actions.php(231): Magefan\Blog\Controller\Adminhtml\Post\Save->filterParams()
#5 /magento2/generated/code/Magefan/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(41): Magefan\Community\Controller\Adminhtml\Actions->_saveAction()
#6 /magento2/app/code/Magefan/Community/Controller/Adminhtml/Actions.php(108): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->_saveAction()
#7 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magefan\Community\Controller\Adminhtml\Actions->execute()
#8 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent()
#9 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}()
#10 /magento2/generated/code/Magefan/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(23): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins()
#11 /magento2/lib/internal/Magento/Framework/App/Action/Action.php(111): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->execute()
#12 /magento2/app/code/Magento/Backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#13 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#14 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent()
#15 /magento2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(145): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}()
#16 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#17 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}()
#18 /magento2/generated/code/Magefan/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(50): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins()
#19 /magento2/lib/internal/Magento/Framework/App/FrontController.php(245): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->dispatch()
#20 /magento2/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#21 /magento2/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#22 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#23 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#24 /magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#25 /magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#26 /magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#27 /magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#28 /magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#29 /magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#30 /composer/vendor/cpriego/valet-linux/server.php(232): require('...')
#31 {main}
```

**Comment by ppeyman** [comment]
> 



> I still don't see the post contents. What should I do? Additionally, it asks me for a license key.

for widget in pagebuilder use like below : 


![image](https://user-images.githubusercontent.com/13271466/232819695-1f8271e8-7716-4798-8365-b8d3b7df93c3.png)


and 


![image](https://user-images.githubusercontent.com/13271466/232819865-1653ae3a-a6fd-497a-bd1d-a596526e73af.png)


then add and test 


Enter 1 for license
I left it open for you to solve the problem
Of course, my Magento is 2.4.5 
if you need new version i should download new version.

**Comment by vovayatsyuk** [comment]
Yes, please download the fixed version.

**Comment by ppeyman** [comment]
Hi dear please give me your Email to send full version for you .

**Comment by vovayatsyuk** [comment]
Fixed: https://github.com/breezefront/module-breeze-magefan-blog/commit/652a5fe6fcb6d660fa85dc69dbd43ea5ca5d6678

<details markdown=1><summary>View Screenshot</summary>

![image](https://github.com/breezefront/module-breeze-magefan-blog/assets/306080/89b529ca-89e0-4ff5-bd03-5af780988841)
</details>
